{"name": "test_5[4-5-6]", "status": "failed", "statusDetails": {"message": "AssertionError: assert ((4 * 5) + 6) == 5", "trace": "x = 4, y = 5, z = 6\n\n    @pytest.mark.parametrize(\"x, y, z\", [(1,2,3), (4,5,6),(7,8,9),(1,2,3)])\n    def test_5(x, y, z):\n>       assert x * y + z == 5\nE       assert ((4 * 5) + 6) == 5\n\ntest_4.py:6: AssertionError"}, "parameters": [{"name": "x", "value": "4"}, {"name": "y", "value": "5"}, {"name": "z", "value": "6"}], "start": 1639816810257, "stop": 1639816810258, "uuid": "8e363860-d009-42e3-bcfd-dc646e60ff13", "historyId": "8ef0f9024d111f28af2f675f811f3950", "testCaseId": "54c5933bbf5498919612b4ec9a952f13", "fullName": "test_4#test_5", "labels": [{"name": "suite", "value": "test_4"}, {"name": "host", "value": "Ani-PC"}, {"name": "thread", "value": "8160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_4"}]}